/**
 * Ministry routes design reminder:
 * Each page gives one visitor intent a clear home. Use specific ministry copy,
 * strong Poppins hierarchy, Hope Teal accents and direct paths to participation.
 */
import { Field, MandateForm } from "@/components/MandateForm";
import { MinistryLayout, PageHero, SectionHeading } from "@/components/MinistryLayout";
import { ArrowRight, ArrowUpRight, BookOpenText, Check, Copy, HandCoins, HeartHandshake, Mail, MapPinned, MessageCircle, Phone, Quote, Sparkles, UsersRound } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";

const founder = "https://raw.githubusercontent.com/theebenezeretim/great-mandate-ministries/main/public/images/pastor-solomon-ufuoma.jpg";
const gallery = "https://raw.githubusercontent.com/theebenezeretim/great-mandate-ministries/main/public/images/mandate-outreach-placeholder.jpg";
const marketEvangelismPhoto = "https://raw.githubusercontent.com/theebenezeretim/great-mandate-ministries/main/public/images/market-evangelism-2026.jpg";
const mark = "https://raw.githubusercontent.com/theebenezeretim/great-mandate-ministries/main/public/images/mandate-mission-mark.png";

const focusAreas = [
  ["Widows", "Care that strengthens dignity and hope."], ["Orphanages", "Compassion expressed in practical service."],
  ["Prisoners", "The Gospel carried beyond closed doors."], ["Market evangelism", "Faith brought into everyday life."],
  ["Schools", "A message of purpose for the next generation."], ["Crusades", "Gathering hearts around Christ and His works."],
];

const arms = [
  ["Compassion Outreach", "Practical care for widows, orphanages and people in need."], ["Market Evangelism", "The Gospel carried into everyday places and conversations."],
  ["Schools & Youth", "A message of faith, identity and purpose for the next generation."], ["Crusades & Missions", "Gathering communities around Christ and His life-transforming works."],
];

const messages = ["Wonders of Sowing into Kingdom Advancement Endeavours", "Building Faith for Triumph in Hard Times"];
const archive = ["Market Evangelism", "Prison Visits", "Orphanage Visits", "Widows Care", "School Outreach", "Crusades"];

function PageCta({ href, children, outline = false }: { href: string; children: React.ReactNode; outline?: boolean }) {
  return <Link className={`button ${outline ? "button--ghost" : "button--gold"}`} href={href}>{children}<ArrowRight size={17} /></Link>;
}

export function AboutPage() {
  return <MinistryLayout><PageHero eyebrow="About the ministry" title={<>Faith expressed through <em>His works.</em></>} lead="The Great Mandate Outreach Ministries carries the Gospel into places where compassionate care, prayer and practical service are needed."><PageCta href="/outreaches">See our outreaches</PageCta></PageHero><section className="route-section route-section--mist"><div className="container route-two-column"><div><SectionHeading eyebrow="Our mandate" title="A calling received in prayer and carried into the world." copy="The ministry began after Pastor Solomon Ufuoma stepped away from five years of faithful service, waited on the Lord in prayer and received a clear mandate for compassionate outreach." /><p className="route-copy">The first outreach took place on 10 October 2024. Since then, the ministry has held to a simple conviction: Christ is glorified when faith is seen in works of love.</p></div><div className="route-quote"><Quote size={34} /><blockquote>“Pure and undefiled religion before God the Father is this: to look after orphans and widows in their distress...”</blockquote><span>James 1:27</span></div></div></section><section className="route-section"><div className="container"><SectionHeading eyebrow="What guides us" title="Vision, mission and values." /><div className="route-value-grid"><article><span>Vision</span><h3>Bringing joy and solace to humanity in all spheres of life.</h3></article><article><span>Mission</span><h3>To see Christ glorified through His works.</h3></article><article><span>Core values</span><h3>Christ-centred. Excellence and modesty. The Way, the Truth and the Life.</h3></article></div></div></section><section className="route-banner"><div className="container"><div><p className="eyebrow eyebrow--hero"><span />Walk with the mission</p><h2>There is room for your prayer, service and giving.</h2></div><PageCta href="/partner">Partner with us</PageCta></div></section></MinistryLayout>;
}

export function FounderPage() {
  return <MinistryLayout><PageHero eyebrow="Meet the founder" title={<>Pastor Solomon <em>Ufuoma</em></>} lead="Founder and Vision Bearer of The Great Mandate Outreach Ministries."><PageCta href="/contact">Contact the ministry</PageCta></PageHero><section className="route-section"><div className="container founder-route"><div className="founder-route__image"><img src={founder} alt="Pastor Solomon Ufuoma" /><p>“A costly call is still worth obeying.”</p></div><article><p className="eyebrow"><span />A life yielded to service</p><h2>Pastor Solomon Ufuoma</h2><p className="route-meta">Born 31 May 1984 · Agparho, Odele North LGA, Delta State</p><p>A man of deep faith, Pastor Solomon believes strongly in Jesus Christ, the power of faith, and the prosperity God has ordained for His people. He left a comfortable place of service to answer an uncompromising call to ministry.</p><p>He is married to Amaka Regina Etaedafe. Together, they carry a burden to serve faithfully and make Christ known through practical love.</p><div className="founder-route__signoff"><img src={mark} alt="" /><span>Founder &amp; Vision Bearer</span></div></article></div></section><section className="route-section route-section--blue"><div className="container route-two-column"><div><SectionHeading eyebrow="The calling" title="Prayer became a public work of compassion." /><p>The ministry exists to serve people with dignity, speak the Gospel clearly and make room for others to take part.</p></div><Link className="button button--gold" href="/outreaches">See the outreach work <ArrowRight size={17} /></Link></div></section></MinistryLayout>;
}

export function OutreachesPage() {
  return <MinistryLayout><PageHero eyebrow="Outreaches" title={<>The Gospel carried into <em>everyday places.</em></>} lead="Our outreach work meets people where they are, with prayer, practical care and the message of Christ."><PageCta href="/partner">Serve with us</PageCta></PageHero><section className="route-section"><div className="container"><SectionHeading eyebrow="Ministry arms" title="Different expressions of one calling." copy="Each arm gives the ministry a clear way to serve people and communities." /><div className="route-card-grid">{arms.map(([title, copy]) => <article className="route-arm-card" key={title}><h3>{title}</h3><p>{copy}</p><Link href="/partner">Join this work <ArrowUpRight size={17} /></Link></article>)}</div></div></section><section className="route-section route-section--mist"><div className="container route-two-column"><div><SectionHeading eyebrow="Who we reach" title="People and places held before God in prayer." /><p className="route-copy">The ministry makes space for care, listening and a clear witness of Christ across these outreach areas.</p></div><div className="route-focus-list">{focusAreas.map(([name, copy]) => <div key={name}><strong>{name}</strong><p>{copy}</p></div>)}</div></div></section><section className="route-banner"><div className="container"><div><p className="eyebrow eyebrow--hero"><span />Be part of the work</p><h2>Give time, prayer or resources to the next outreach.</h2></div><PageCta href="/partner">Partner with us</PageCta></div></section></MinistryLayout>;
}

export function SermonsPage() {
  return <MinistryLayout><PageHero eyebrow="Sermons" title={<>Hear the <em>Word.</em></>} lead="Scripture-rooted teaching for faith, purpose and a life that bears fruit."><PageCta href="/contact">Ask about a message</PageCta></PageHero><section className="route-section"><div className="container"><div className="route-archive-intro"><SectionHeading eyebrow="Teaching archive" title="Recent messages." copy="The full teaching library is being prepared. These messages are available to ask about through the ministry team." /><span><BookOpenText size={18} />More messages coming soon</span></div><div className="route-sermon-grid">{messages.map((message, index) => <article key={message}><span>Message 0{index + 1}</span><h3>{message}</h3><p>Message details and media links will be published here as they are released.</p><Link href="/contact">Ask about this message <ArrowRight size={16} /></Link></article>)}</div></div></section><section className="route-section route-section--mist"><div className="container route-two-column"><div><SectionHeading eyebrow="Stay informed" title="Receive new teaching notices." copy="Use the contact page to ask the team about a teaching, ministry event or future sermon release." /></div><PageCta href="/contact">Contact the team</PageCta></div></section></MinistryLayout>;
}

export function EventsPage() {
  return <MinistryLayout><PageHero eyebrow="Crusades & events" title={<>Be there when the next outreach is <em>announced.</em></>} lead="Confirmed crusades and outreach dates will be published here. Join the waitlist to hear first."><PageCta href="/partner">Support an outreach</PageCta></PageHero><section className="route-section route-section--mist"><div className="container route-event-grid"><div><SectionHeading eyebrow="Upcoming gatherings" title="The next date will appear here." copy="No new outreach date has been confirmed yet. The ministry will contact the waitlist when a crusade or outreach is announced." /><div className="route-empty-state"><MapPinned size={25} /><p>Event announcements coming soon</p></div></div><div className="route-form-card"><p className="pastoral-kicker">Receive the call to gather</p><h2>Join the event waitlist</h2><p>Share your details and expectation for the next ministry event.</p><MandateForm formName="Event Waitlist" submitLabel="Keep me informed"><Field label="Name"><input name="name" required placeholder="Your name" /></Field><Field label="Email"><input name="email" type="email" required placeholder="you@example.com" /></Field><Field label="WhatsApp number"><input name="whatsapp" type="tel" required placeholder="+234" /></Field><Field label="Profession"><input name="profession" placeholder="Your profession" /></Field><Field label="What do you hope to receive?"><textarea name="expectation" rows={3} placeholder="Share your expectation" /></Field></MandateForm></div></div></section></MinistryLayout>;
}

export function GalleryPage() {
  return <MinistryLayout><PageHero eyebrow="Outreach gallery" title={<>A growing record of <em>service.</em></>} lead="Photographs and videos from verified ministry outreaches will be kept here as the work continues."><PageCta href="/outreaches">See the outreach work</PageCta></PageHero><section className="route-section"><div className="container"><div className="route-archive-intro"><SectionHeading eyebrow="The archive" title="Photos will be added as each outreach is documented." /><span>Verified ministry images only</span></div><div className="route-gallery-grid">{archive.map((item, index) => <article key={item}><div>{index === 0 ? <img src={marketEvangelismPhoto} alt="The Great Mandate Market Evangelism outreach" /> : index === 1 ? <img src={gallery} alt="Illustrative placeholder for future ministry outreach photography" /> : <span>TGMO</span>}</div><p>{index === 0 ? "Authentic outreach photograph" : "Outreach photograph awaiting upload"}</p><h3>{item}</h3></article>)}</div></div></section><section className="route-section route-section--blue"><div className="container route-two-column"><div><SectionHeading eyebrow="Share media" title="Do you have an approved photograph from an outreach?" /><p>Send it to the ministry team for review before it is added to this archive.</p></div><PageCta href="/contact">Contact the team</PageCta></div></section></MinistryLayout>;
}

export function PrayerPage() {
  return <MinistryLayout><PageHero eyebrow="Prayer & testimonies" title={<>We believe God still <em>answers.</em></>} lead="Send a prayer request or share a testimony so the ministry team can stand with you and encourage others."><PageCta href="/partner">Stand in prayer</PageCta></PageHero><section className="route-section"><div className="container route-prayer-grid"><div><SectionHeading eyebrow="A place of agreement" title="Send a prayer request." copy="Prayer requests may be shared with the ministry prayer team for agreement in prayer." /><div className="route-prayer-note"><Sparkles size={20} /><p>Choose anonymous submission if you prefer not to include your name.</p></div><div className="route-form-card route-form-card--light"><MandateForm formName="Prayer Request" submitLabel="Bring this request in prayer"><Field label="Name (optional)"><input name="name" placeholder="Your name" /></Field><Field label="Email or WhatsApp"><input name="contact" required placeholder="How can the team follow up?" /></Field><Field label="Prayer request"><textarea name="prayer_request" rows={5} required placeholder="Share your request here" /></Field><label className="simple-check"><input name="anonymous" type="checkbox" /><span>Submit anonymously</span></label></MandateForm></div></div><div className="route-testimony-card"><p className="eyebrow eyebrow--hero"><span />Testimonies</p><h2>Share what God has done.</h2><p>Approved testimonies may be shared to encourage the ministry community.</p><MandateForm formName="Testimony" submitLabel="Share testimony" compact><Field label="Name"><input name="name" placeholder="Your name" /></Field><Field label="Your testimony"><textarea name="testimony" rows={6} required placeholder="Tell us what God has done" /></Field></MandateForm><div className="route-testimony-empty"><Quote size={19} />Verified testimonies will appear here.</div></div></div></section></MinistryLayout>;
}

export function PartnerPage() {
  return <MinistryLayout><PageHero eyebrow="Partner with us" title={<>There is a place for your hands, heart and <em>prayer.</em></>} lead="Partner through prayer, giving, on-ground service or by becoming part of the ministry family."><PageCta href="/give">Give to the work</PageCta></PageHero><section className="route-section route-section--burgundy"><div className="container route-partner-grid"><div><SectionHeading eyebrow="A practical step of faith" title="Join the work of the mandate." copy="The ministry receives every expression of support with gratitude and follows up where appropriate." /><div className="route-participation-list"><span><HeartHandshake size={18} />Prayer support</span><span><HandCoins size={18} />Financial partnership</span><span><UsersRound size={18} />Outreach service</span></div></div><div className="route-form-card"><MandateForm formName="Partner with us" submitLabel="Take this step with us"><div className="form-grid--two"><Field label="Full name"><input name="name" required placeholder="Your name" /></Field><Field label="Email address"><input name="email" type="email" required placeholder="you@example.com" /></Field></div><Field label="Phone / WhatsApp"><input name="phone" type="tel" required placeholder="+234" /></Field><fieldset className="check-group"><legend>How would you like to be involved?</legend><div className="check-grid">{["Prayer Partner", "Financial Partner", "Volunteer at Outreaches", "Join the Ministry"].map((item) => <label key={item}><input type="checkbox" name="involvement" value={item} /><span>{item}</span></label>)}</div></fieldset><Field label="A message for the ministry"><textarea name="message" rows={4} placeholder="Tell us how you would like to connect." /></Field></MandateForm></div></div></section></MinistryLayout>;
}

export function GivePage() {
  const [copied, setCopied] = useState(false);
  async function copyAccount() { await navigator.clipboard?.writeText("2006711996"); setCopied(true); window.setTimeout(() => setCopied(false), 2200); }
  return <MinistryLayout><PageHero eyebrow="Give" title={<>Sow into <em>The Great Mandate.</em></>} lead="Your giving helps carry the Gospel and compassionate care to people, places and communities in need."><PageCta href="/partner">Partner with us</PageCta></PageHero><section className="route-section route-section--blue"><div className="container route-give-grid"><div><SectionHeading eyebrow="A gift placed in faithful hands" title="Partner through giving." /><p className="route-copy">“God loves a cheerful giver.” <strong>2 Corinthians 9:7</strong></p><p className="route-copy">Online giving will be added through Paystack or Flutterwave when the ministry is ready to receive card and transfer payments online.</p></div><div className="route-bank-card"><div><HandCoins size={23} /><p>Bank transfer details</p></div><dl><dt>Bank</dt><dd>FCMB</dd><dt>Account name</dt><dd>The Great Mandate Outreach Ministries</dd><dt>Account number</dt><dd className="route-bank-card__account">2006711996 <button type="button" onClick={copyAccount}>{copied ? <Check size={16} /> : <Copy size={16} />}{copied ? "Copied" : "Copy"}</button></dd></dl></div></div></section></MinistryLayout>;
}

export function ContactPage() {
  return <MinistryLayout><PageHero eyebrow="Contact" title={<>Let us walk with <em>you.</em></>} lead="For ministry enquiries, outreach partnerships or a conversation with the team, use the details below or send a message."><PageCta href="/prayer">Send a prayer request</PageCta></PageHero><section className="route-section"><div className="container route-contact-grid"><div><SectionHeading eyebrow="Reach out" title="The team is ready to listen." /><div className="route-contact-list"><a href="mailto:solomonufuoma16@gmail.com"><Mail size={19} /><span><small>Email</small>solomonufuoma16@gmail.com</span></a><a href="tel:+2348106903151"><Phone size={19} /><span><small>Phone</small>+234 810 690 3151</span></a><a href="https://wa.me/2347050722808" target="_blank" rel="noreferrer"><MessageCircle size={19} /><span><small>WhatsApp</small>+234 705 072 2808</span></a></div></div><div className="route-form-card"><p className="pastoral-kicker">Send a message</p><h2>How may we serve you?</h2><MandateForm formName="Contact" submitLabel="Send a word to the team"><Field label="Your name"><input name="name" required placeholder="Your name" /></Field><Field label="Email address"><input name="email" type="email" required placeholder="you@example.com" /></Field><Field label="Message"><textarea name="message" rows={6} required placeholder="How may we serve you?" /></Field></MandateForm></div></div></section></MinistryLayout>;
}
